### ISSUE TITLE
Adjust height of snack bar

### ISSUE THREAD

**Issue by Raider-hub** [LanarsInc/top-snackbar-flutter#39]
hey please can you add a feature to allow adjustment of the snack bar. height and width

**Comment by vikmind** [comment]
Hi @Raider-hub, you could create your own widget instead of the one provided by the library. Check the source code of the [`CustomSnackBar`](https://github.com/LanarsInc/top-snackbar-flutter/blob/main/lib/custom_snack_bar.dart) or just start from simple `Container` and add adjustments suitable for your project.
